services:
  postgres:
    image: postgres:15
    container_name: postgres-itq
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=document_service_itq
    ports:
      - '5432:5432'