server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: document-service-itq-test-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/document_service_itq
    username: postgres
    password: 123

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml